server:
  port: 28761
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    enabled: false
    sampler:
      percentage: 1

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:28761/eureka/
  server:
    enable-self-preservation: false

logging:
  file: logs/eurake-server.log
  level:
    root: info

management:
  security:
    enabled: false